// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA_j5TQBcXvOw0YG36ooIuHXHqTqC4Qv4',
    appId: '1:836908177238:web:a84adb0fc8223aa79ca8f7',
    messagingSenderId: '836908177238',
    projectId: 'fixbuddypartner',
    authDomain: 'fixbuddypartner.firebaseapp.com',
    storageBucket: 'fixbuddypartner.firebasestorage.app',
    measurementId: 'G-YZ2SYXF04E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjDtM8GWpxiHlwTstn6md-VaoDjz9PhM',
    appId: '1:836908177238:android:e55c669ea5408e849ca8f7',
    messagingSenderId: '836908177238',
    projectId: 'fixbuddypartner',
    storageBucket: 'fixbuddypartner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHlPETrimRSaBHnJ9MAuyrqngNHv-TJFY',
    appId: '1:836908177238:ios:a82285260d024a929ca8f7',
    messagingSenderId: '836908177238',
    projectId: 'fixbuddypartner',
    storageBucket: 'fixbuddypartner.firebasestorage.app',
    iosBundleId: 'com.example.fixbuddyPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHlPETrimRSaBHnJ9MAuyrqngNHv-TJFY',
    appId: '1:836908177238:ios:a82285260d024a929ca8f7',
    messagingSenderId: '836908177238',
    projectId: 'fixbuddypartner',
    storageBucket: 'fixbuddypartner.firebasestorage.app',
    iosBundleId: 'com.example.fixbuddyPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA_j5TQBcXvOw0YG36ooIuHXHqTqC4Qv4',
    appId: '1:836908177238:web:a384c85063fdb9339ca8f7',
    messagingSenderId: '836908177238',
    projectId: 'fixbuddypartner',
    authDomain: 'fixbuddypartner.firebaseapp.com',
    storageBucket: 'fixbuddypartner.firebasestorage.app',
    measurementId: 'G-E0T88LTZGJ',
  );

}